#!/usr/bin/env bash
# check_tooltips.sh — fail when the viewer shows a native title= tooltip instead of a themed data-tip.
# Kind: check
# Spec: docs/specs/themed-tooltip-rollout/
#
# Usage:
#   scripts/check/check_tooltips.sh
#   Exit 0 = no finding · exit 1 = at least one finding · exit 2 = the check could not run.
#
# Finding: one line per defect, prefixed with its test id.
#          TS1 a hand-written page carries a native title= on an element other than iframe / abbr / svg.
#          TS2 app.js writes a native title (a property assignment or setAttribute).
#          TS3 tooltip.js is missing, has lost part of its contract, or index.html does not load it.
#          TS4 style.css lacks the .fui-tip rule, or the rule is not fixed-position and token-only.
#          TS5 a list of shipped files does not name tooltip.js.
#          Fix the named line: a hint rides data-tip (ui_and_styling.md § Tooltips, owner ruling 2026-09-26).
# Why:     lookin has no Go and no build step, so the platform's T1 tooltip scan is a shell check here.
#          The dev-method deck is generated by the deck engine and published in the presentations repo, not here.
# Needs:   nothing — reads files in this repo only.
# See:     docs/specs/themed-tooltip-rollout/tests.md · foundation-ui/tooltip_theme_test.go (the reference scan).
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

case "${1:-}" in
	-h|--help) awk 'NR>1 && /^#/ {sub(/^# ?/, ""); print; next} NR>1 {exit}' "$0"; exit 0 ;;
esac

command -v python3 >/dev/null 2>&1 || { echo "check_tooltips: python3 is required for the tag scan" >&2; exit 2; }

found=0
finding() { printf '%s\n' "$*"; found=1; }

# TS1 — the attribute belongs to the nearest preceding '<'; iframe / abbr / svg keep title= (a name).
ts1="$(python3 - "$ROOT/index.html" "$ROOT/landing.html" <<'PY'
import re, sys
allowed = {"iframe", "abbr", "svg"}
for path in sys.argv[1:]:
    src = open(path, encoding="utf-8").read()
    for m in re.finditer(r'\stitle="', src):
        lt = src.rfind("<", 0, m.start())
        tag = re.match(r'<([a-zA-Z][a-zA-Z0-9-]*)', src[lt:]) if lt >= 0 else None
        if tag and tag.group(1).lower() not in allowed:
            line = src.count("\n", 0, m.start()) + 1
            print(f"TS1 {path.rsplit('/', 1)[-1]}:{line} <{tag.group(1)}> carries a native title=")
PY
)" || { echo "check_tooltips: the tag scan failed" >&2; exit 2; }
[ -n "$ts1" ] && finding "$ts1"

# TS2 — document.title is the page name, not a hint.
while IFS= read -r hit; do
	[ -n "$hit" ] && finding "TS2 app.js:$hit"
done < <(sed 's/document\.title//g' "$ROOT/app.js" | command grep -nE "\.title[[:space:]]*=[^=]|setAttribute\([[:space:]]*['\"]title['\"]" || true)

# TS3 — the script ships, keeps its contract, and the page loads it.
if [ ! -s "$ROOT/tooltip.js" ]; then
	finding "TS3 tooltip.js is missing or empty"
else
	for want in "'tooltip'" textContent focusin Escape data-tip aria-describedby "'mousemove'" getBoundingClientRect; do
		command grep -qF -- "$want" "$ROOT/tooltip.js" || finding "TS3 tooltip.js lacks $want"
	done
	command grep -qF innerHTML "$ROOT/tooltip.js" && finding "TS3 tooltip.js assembles markup (innerHTML)"
fi
command grep -qF 'src="tooltip.js"' "$ROOT/index.html" || finding "TS3 index.html does not load tooltip.js"

# TS4 — the LAST .fui-tip rule is the floor's (a token bridge precedes it).
ts4="$(python3 - "$ROOT/style.css" <<'PY'
import re, sys
css = re.sub(r'/\*.*?\*/', '', open(sys.argv[1], encoding="utf-8").read(), flags=re.S)
rule = ""
for sel, body in re.findall(r'([^{}]+)\{([^{}]*)\}', css):
    if " ".join(sel.split()) == ".fui-tip":
        rule = " ".join(body.split())
if not rule:
    print("TS4 style.css has no .fui-tip rule")
    sys.exit(0)
for tok in ("var(--bg-card)", "var(--fg)", "var(--border)", "var(--r-md)"):
    if tok not in rule:
        print(f"TS4 .fui-tip does not use {tok}")
if "position: fixed" not in rule:
    print("TS4 .fui-tip is not position: fixed")
if "#" in rule:
    print("TS4 .fui-tip carries a raw hex colour")
if re.search(r'rgba?\(\s*[0-9]', rule):
    print("TS4 .fui-tip carries a raw rgb()/rgba() literal")
PY
)" || { echo "check_tooltips: the style scan failed" >&2; exit 2; }
[ -n "$ts4" ] && finding "$ts4"

# TS5 — a deploy must never serve an index.html that points at a script it did not ship.
for list in deploy.sh pipelines/OPS-deploy_lookin.md; do
	command grep -qF 'tooltip.js' "$ROOT/$list" || finding "TS5 $list does not ship tooltip.js"
done

exit $found
